POST http://localhost:4500/users/register
Content-Type: application/json

{
    "firstName":"John",
    "lastName":"Doe",
    "email":"mail@mail.com",
    "password":"12345"
}


###
GET  http://localhost:4500/users/all
Content-Type: application/json


###
GET  http://localhost:4500/products/1fc7b941-0af0-4370-9ca9-1f629760
Content-Type: application/json


###
DELETE   http://localhost:4500/products/1fc7b941-0af0-4370-9ca9-1f6297606b66
Content-Type: application/json


###
PUT    http://localhost:4500/products/98150e13-a20f-4790-a97c-22363828a0
Content-Type: application/json

{
    "productName": "Coffee",
    "description":"A cold cup of coffee",
    "category":"Tea",
    "stockQuantity":3,
    "regularPrice":245,
    "salePrice":235,
    "image":"dfcddbbjrbjbrg"
}


###

GET  http://localhost:4500/products
Content-Type: application/json


###


POST http://localhost:4500/cart
Content-Type: application/json

{
    "userId":"2e96b6aa-04cc-4c65-a37c-495675b6ed45",
    "productId":"54b5916d-10c6-45d6-b94c-4db1576451f0",
    "orderedQuantity": 4
}